---
# variables for handing out files, file_items should be a list.
# add file items as many as you want.
# Format explain:
#
#file_items:
#  - src_file:  source file name, eg. filename.txt
#    dest_file: target file path and name, eg./path_to_file/filename.txt
#    file_owner: target file owner, eg. zhangsan
#    file_group: target file group, eg. staff
#    file_mode: target file privilege, eg. '0644' or u+x, g+w, o-r or u=rwx,g=r,o=r
#
#  - src_files:
#    ...
#
# Example: BEGIN
#
#file_items:
#  - src_file:  foo.txt
#    dest_file: /path_to_file/foo.txt
#    file_owner: zhangsan
#    file_group: staff
#    file_mode: '0644'
#
# Example END

file_items:
  - src_file: foo.txt
    dest_file: /tmp/vagrant/foo/foo.txt
    file_owner: vagrant
    file_group: vagrant
    file_mode: '0644'

  - src_file: bar.txt
    dest_file: /tmp/ansible/bar.txt
    file_owner: ansible
    file_group: opergrp
    file_mode: '0754'

  - src_file: foobar.txt
    dest_file: /home/vagrant/foobar/foobar/foobar/foobar.txt
    file_owner: vagrant
    file_group: vagrant
    file_mode: '0640'

  - src_file: helloworld.txt
    dest_file: /home/ansible/helloworld.txt
    file_owner: ansible
    file_group: opergrp
    file_mode: '0755'
