---

- name: hand out files to target
  hosts: all
  become: True
  gather_facts: False
  vars_files:
    - files-list.yml

  tasks:
    - name: check wether the base directory exist
      stat:
        path: "{{ item.dest_file|dirname }}"
      register: basedir
      with_items:
        - "{{ file_items }}"

#    - debug:
#        var: basedir
#
    - set_fact:
        basedir_results: "{{ basedir.results }}"

#    - debug:
#        msg: "directory is {{ item.stat.path|default('null') }}, isdir is {{ item.stat.isdir|default('null') }} since existing is {{ item.stat.exists }}"
#      with_items:
#        - "{{ basedir_results }}"
#      when: not item.stat.exists
#
    - name: make the base directory
      file:
        path: "{{ item.item.dest_file|dirname }}"
        owner: "{{ item.item.file_owner }}"
        group: "{{ item.item.file_group }}"
        state: directory
      with_items:
        - "{{ basedir_results }}"
      when: not item.stat.exists

    - name: copy files to target
      copy:
        src: "{{ item.src_file }}"
        dest: "{{ item.dest_file }}"
        owner: "{{ item.file_owner }}"
        group: "{{ item.file_group }}"
        mode: "{{ item.file_mode }}"
      with_items:
        - "{{ file_items }}"
      notify:  remove source files

  handlers:
    - name: remove source files
      become: False
      file:
        path: files/{{ item.src_file }}
        state: absent
      with_items:
        - "{{ file_items }}"
      connection: local
